### ISSUE TITLE
ArtDecor to IG - Status, Tooling and Howto

### ISSUE THREAD

**Issue by psavva** [ahdis/artdecor2ig#1]
Dear @oliveregger 

I'm very interested in converting the ArtDecor Value Sets to FHIR, specifically for the Cross Border NCP project for Cyprus, and would like to know how to use this repository, and how we are able to convert the ArtDecor Value Sets into FHIR valuesets and configurations?

Any pointers, and info would be greatly appreciated.

**Comment by oliveregger** [comment]
hi @psavva 

art-decor has directly an API to retrieve FHIR ValueSet, see https://art-decor.org/mediawiki/index.php?title=FHIR_URIs?

what we did for our projects was to adapt the ValueSet in addition with xslt that we can use them in our implementation guide, because we have some special requirements.

the first call is to get the ValueSet directly form art-decor, e.g:
http://art-decor.org/fhir/4.0/${project}/ValueSet/${templateId}

see https://github.com/ahdis/artdecor2ig/blob/master/ch-epr-/build.xml#L57

then we do some adaptions that it can be used in our ig:
https://github.com/ahdis/artdecor2ig/blob/master/ch-epr-/xslt/adaptValueSetToIg.xsl

does this help? the process is done per art-decor project and a specific xslt is then written, that means you need to have java/[ant](https://ant.apache.org/) and xslt 2.0 installed if you wan't to run it, but i would only advise to that if you have want to start using xslt to adapt the ValueSet which might be not necessary depending on your project.

if you have ant/java installed you go to the project in the command line and just execute ant, which then will run the build script: 

```
cd ch-epr-
ant
```

hope this helps, otherwise let me know.

**Comment by psavva** [comment]
Thank you very much :)
Highly appreciated.
